# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SevenWestMedia' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'RxSwift', '~> 3.4'
    pod 'RxCocoa', '~> 3.4'
    pod 'SDWebImage', '~>3.8'
    
  target 'SevenWestMediaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
